### ISSUE TITLE
unable to access asr tts resources in ucce cvp 12.5.1

### ISSUE THREAD

**Issue by themeichten** [CiscoDevNet/cvp-sample-code#4]
Hi I'm trying to utilize this sample code and receiving an error utilizing the speech resources.  CCBU_12_5_SpeechServer-3-SS_EXCEPTION: %[exception=com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: (ByteArrayInputStream); line: 1, column: 3]][message_string=Unable to get the credential Provider for Google Speech Service]: Server has caught an exception

have you seen this error?
Thanks Mark

**Comment by rohinda** [comment]
Can you please check while configuring the CVA you have given the service account id same as your GCP project name.

**Comment by rohinda** [comment]
No Response from 10 days so closing the comment, let me know if the issue still exist.
